CREATE TABLE KHOA(
	MAKHOA CHAR(4) NOT NULL,
	TENKHOA VARCHAR(30) NOT NULL,
	NAMTHANHLAP INT,
	PRIMARY KEY(MAKHOA)
)
--NHAP DU LIEU VAO BANG KHOA
insert into KHOA values
('C1', 'CNTT', 1999),
('B2', 'KHTT', 2004),
('A1', 'KD', 2007)
CREATE TABLE SINHVIEN
(
	TEN CHAR(20) NOT NULL,
	MSSV CHAR(10) NOT NULL,
	NAMSINH INT,
	MAKHOA CHAR(4) NOT NULL,
	PRIMARY KEY(MSSV),
	FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)
)
--NHAP DU LIEU VAO BANG SINHVIEN
insert into SINHVIEN values
('NGUYEN HA MY', '552200066', 2004, 'C1'),
('VO THI THANH NGAN', '552200131', 2004, 'C1'),
('DANH NGUYEN NHUT AN', '552200008', 2004, 'C1')
CREATE TABLE MONHOC(
	TENMH CHAR(20) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	TINCHI INT,
	MAKHOA CHAR(4) NOT NULL,
	PRIMARY KEY(MAMH),
	FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)
)
--NHAP DU LIEU VAO BANG MONHOC
insert into MONHOC values
('CSDL', 'M1', 4, 'C1'),
('XSTK', 'N1', 4, 'C1'),
('CTDL', 'H1', 4, 'C1')
CREATE TABLE DIEUKIEN(
	MAMH CHAR(10) NOT NULL,
	MAMH_TRUOC CHAR(10) NOT NULL,
	FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	PRIMARY KEY(MAMH_TRUOC)
)
-- NHAP DU LIEU VAO BANG DIEUKIEN
insert into DIEUKIEN values
('M1', 'M11'),
('N1', 'N11'),
('H1', 'H11')
CREATE TABLE HOCPHAN(
	MAHP CHAR(10) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	HOCKY CHAR(5) NOT NULL,
	NAM INT,
	GIAOVIEN CHAR(20) NOT NULL,
	FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	PRIMARY KEY(MAHP)
)
-- NHAP DU LIEU VAO BANG HOC PHAN
insert into HOCPHAN values
('01', 'M1', '2', 1, 'NGUYENTHEHUU'),
('02', 'N1', '5', 3, 'NGUYENTHIHUYNHTRAM'),
('03', 'H1', '4', 2, 'DUNGCAMQUANG')
CREATE TABLE KETQUA(
	MSSV CHAR(10) NOT NULL,
	MAHP CHAR(10) NOT NULL,
	DIEM CHAR(5) NOT NULL,
	FOREIGN KEY(MSSV) REFERENCES SINHVIEN(MSSV),
	FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
)
-- NHAP DU LIEU VAO BANG KET QUA
insert into KETQUA values
('552200066', '01', '10'),
('552200131', '02', '10'),
('552200008', '03', '10')
