CREATE DATABASE QLSV_LAB5
GO
USE QLSV_LAB5
GO
SET DATEFORMAT MDY
GO
CREATE TABLE KHOA(
	MAKHOA CHAR(10) NOT NULL,
	TENKHOA NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_KHOA PRIMARY KEY(MAKHOA)
)
GO
CREATE TABLE SINHVIEN(
	HOSV NVARCHAR(20) NOT NULL,
	TENSV NVARCHAR(15) NOT NULL,
	MASV CHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	PHAI CHAR(5) NOT NULL,
	MAKHOA CHAR(10) NOT NULL,
	CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV),
	CONSTRAINT FK_MAKHOA_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)
)
GO
CREATE TABLE MONHOC(
	TENMH NVARCHAR(20) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	SOTIET INT,
	CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH)
)
GO
CREATE TABLE KETQUA(
	MASV CHAR(10) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	LANTHI INT,
	DIEM INT,
	CONSTRAINT PK_KETQUA PRIMARY KEY(MASV, MAMH, LANTHI),
	CONSTRAINT FK_MASV_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT FK_MAMH_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
)
GO
--NHAP DU LIEU CHO CAC BANG
INSERT INTO KHOA VALUES
('AVAN', 'Khoa anh Van'),
('CNTT', 'Cong Nghe Thong tin'),
('DTVT', 'Dien Tu Vien Thong'),
('QTKD', 'Quan Tri Kinh Doanh')
INSERT INTO SINHVIEN VALUES
('Tran Minh', 'Son', 'S001', '5/1/1985', 'Nam', 'CNTT'),
('Nguyen Quoc', 'Bao', 'S002', '5/15/1986', 'Nam', 'CNTT'),
('Phan Anh', 'Tung', 'S003', '12/20/1983', 'Nam', 'QTKD'),
('Bui Thi Anh', 'Thu', 'S004', '2/1/1985', 'Nu', 'QTKD'),
('Le Thi Lan Anh', 'Anh', 'S005', '7/3/1987', 'Nu', 'DTVT'),
('Nguyen Thi', 'Lam', 'S006', '11/25/1984', 'Nu', 'DTVT'),
('Phan Thi', 'Ha', 'S007', '7/3/1988', 'Nu', 'CNTT'),
('Tran The', 'Dung', 'S008', '10/21/1985', 'Nam', 'CNTT')
GO
INSERT INTO MONHOC VALUES
('Anh Van', 'AV', 45),
('Co So Du Lieu', 'CSDL', 45),
('Ki Thuat Lap Trinh', 'KTLT', 60),
('Ke Toan Tai Chinh', 'KTTC', 45),
('Toan Cao Cap', 'TCC', 60),
('Tin Hoc Van Phong', 'THVP', 30),
('Tri Tue Nhan Tao', 'TTNT', 45)
GO
INSERT INTO KETQUA VALUES
('S001', 'CSDL', 1, 4),
('S001', 'TCC', 1, 6),
('S002', 'CSDL', 1, 3),
('S002', 'CSDL', 2, 6),
('S003', 'KTTC', 1, 5),
('S004', 'AV', 1, 8),
('S004', 'THVP', 1, 4),
('S004', 'THVP', 2, 8),
('S006', 'TCC', 1, 5),
('S007', 'AV', 1, 2),
('S007', 'AV', 2, 9),
('S007', 'KTLT', 1, 6),
('S008', 'AV', 1, 7)
GO
--Cau1
CREATE PROCEDURE CAU1 @Hosv nvarchar(20), @Tensv nvarchar(15), @Masv char(10), @Ngaysinh Date, @Phai char(5), @Makhoa char(10)
AS
BEGIN
	INSERT INTO SinhVien VALUES (@Hosv, @Tensv, @Masv, @Ngaysinh, @Phai, @Makhoa)
END
GO
EXECUTE CAU1 N'Le Cong', N'Tuan', 'S009', '1/3/2004', 'Nam', 'CNTT'
--Cau2
GO
CREATE PROC CAU2 @Hosv nvarchar(20), @Tensv nvarchar(15), @Masv char(10), @Ngaysinh Date, @Phai char(5), @Makhoa char(10)
AS
BEGIN
	IF NOT EXISTS ( SELECT Makhoa FROM KHOA WHERE Makhoa = @Makhoa)
	PRINT 'NOT EXISTS IN KHOA'
	ELSE IF EXISTS ( SELECT MASV FROM SINHVIEN WHERE MASV = @Masv)
	PRINT'EXISTS IN SINHVIEN'
	ELSE IF (((YEAR(GETDATE()) - YEAR(@Ngaysinh)) < 18 OR (YEAR(GETDATE()) - YEAR(@Ngaysinh)) >= 40))
	PRINT 'THERE IS A PERSON WHO IS TOO YOUNG OR TOO OLD TO BEEN ACCEPT'
	ELSE
	INSERT INTO Sinhvien VALUES (@Hosv, @Tensv, @Masv, @Ngaysinh, @Phai, @Makhoa)
END
GO
EXEC CAU2 N'Banh mi' , 'Ruoc', 'S010', '3/22/2010', 'Nu', 'CNTT'
GO
SELECT * FROM SINHVIEN
GO
--CAU3
CREATE PROC CAU3 ( 
	@MASV CHAR(10), 
	@MAMH CHAR(10), 
	@LANTHI INT, 
	@DIEM INT
)
AS
BEGIN
	DECLARE @MASVTONTAI INT
	SET @MASVTONTAI = 
	(
		SELECT COUNT(*)
		FROM SINHVIEN
		WHERE MASV = @MASV
	)
	IF @MASVTONTAI > 0
	BEGIN
		RAISERROR(N'MASV da ton tai', 16, 1)
		RETURN
	END

	DECLARE @MAMHTONTAI INT
	SET @MAMHTONTAI = 
	(
		SELECT COUNT(*)
		FROM MONHOC
		WHERE MAMH = @MAMH
	)
	IF @MAMH > 0
	BEGIN
		RAISERROR(N'MAMH da ton tai', 16, 1)
		RETURN
	END
END
GO
EXEC CAU3 'S001', 'CSDL', 1, 9
GO
--CAU4
CREATE PROC CAU4 @MASV CHAR(10)
AS
BEGIN
	DECLARE @SOLUONGSV INT
	SET @SOLUONGSV = 
	(
		SELECT COUNT(*)
		FROM SINHVIEN
		WHERE MASV = @MASV
	)
	PRINT @SOLUONGSV
END
GO
--CAU5
CREATE FUNCTION CAU5(@MAKHOA CHAR(10))
RETURNS TABLE
AS
RETURN
SELECT * FROM SINHVIEN
WHERE @MAKHOA = MAKHOA
GO
--CAU6
CREATE FUNCTION CAU6()
RETURNS TABLE
AS
RETURN
SELECT COUNT(*) AS N'SLSV' FROM SINHVIEN
GO
SELECT * FROM CAU6()
GO
--CAU8
CREATE FUNCTION CAU8(@MAKHOA CHAR(10))
RETURNS TABLE
AS
RETURN 
SELECT COUNT(*) AS N'SLSV' FROM SINHVIEN
WHERE @MAKHOA = MAKHOA
GO
--
SELECT * FROM CAU8('CNTT')
GO