CREATE DATABASE QUANLYBANHANG
GO
USE QUANLYBANHANG
CREATE TABLE KHACHHANG(
	MAKHACHHANG CHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(50) NOT NULL,
	TENGIAODICH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(40) NOT NULL,
	DIENTHOAI CHAR(15) NOT NULL,
	FAX CHAR(30) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKHACHHANG)
)
CREATE TABLE NHANVIEN(
	MANHANVIEN CHAR(10) NOT NULL,
	HO VARCHAR(20) NOT NULL,
	TEN VARCHAR(15) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL,
	DIACHI VARCHAR(30) NOT NULL,
	DIENTHOAI CHAR(15) NOT NULL,
	LUONGCOBAN INT,
	PHUCAP INT,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANHANVIEN)
)
CREATE TABLE DONDATHANG(
	SOHOADON INT,
	MAKHACHHANG CHAR(10) NOT NULL,
	MANHANVIEN CHAR(10) NOT NULL,
	NGAYDATHANG DATE NOT NULL,
	NGAYGIAOHANG DATE NOT NULL,
	NGAYCHUYENHANG DATE NOT NULL,
	NOIGIAOHANG VARCHAR(30) NOT NULL,
	CONSTRAINT PK_DONDATHANG PRIMARY KEY(SOHOADON),
	CONSTRAINT FK_MANHANVIEN_NHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	CONSTRAINT FK_MAKHACHHANG_KHACHHANG FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)
CREATE TABLE NHACUNGCAP(
	MACONGTY VARCHAR(30) NOT NULL,
	TENCONGTY VARCHAR(30) NOT NULL,
	TENGIAODICH NVARCHAR(50) NOT NULL,
	DIACHI VARCHAR(30) NOT NULL,
	DIENTHOAI CHAR(15) NOT NULL,
	FAX CHAR(30) NOT NULL,
	EMAIL NVARCHAR(40) NOT NULL,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MACONGTY)
)
CREATE TABLE LOAIHANG(
	MALOAIHANG VARCHAR(20) NOT NULL,
	TENLOAIHANG VARCHAR(30) NOT NULL,
	CONSTRAINT PK_LOAIHANG PRIMARY KEY(MALOAIHANG)
)
CREATE TABLE MATHANG(
	MAHANG VARCHAR(20) NOT NULL,
	TENHANG VARCHAR(20) NOT NULL,
	MACONGTY VARCHAR(30) NOT NULL,
	MALOAIHANG VARCHAR(20) NOT NULL,
	SOLUONG INT,
	DONVITINH VARCHAR(20) NOT NULL,
	GIAHANG INT,
	CONSTRAINT PK_MATHANG PRIMARY KEY(MAHANG),
	CONSTRAINT FK_MACONGTY_NHACUNGCAP FOREIGN KEY(MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	CONSTRAINT FK_MALOAIHANG_LOAIHANG FOREIGN KEY(MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
)
CREATE TABLE CHITIETDATHANG(
	SOHOADON INT,
	MAHANG VARCHAR(20) NOT NULL,
	GIABAN INT,
	SOLUONG INT,
	MUCGIAMGIA CHAR(10),
	CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY(SOHOADON, MAHANG),
	CONSTRAINT FK_SOHOADON_DONDATHANG FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	CONSTRAINT FK_MAHANG_MATHANG FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG)
)
--bo sung rang buoc thiet lap gia tri mac dinh bang 1 cho cot soluong va bang 0 cho cot mucgiamgia trong bang chitietdathang
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT DF_SOLUONG DEFAULT 1 FOR SOLUONG
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT DF_MUCGIAMGIA DEFAULT 0 FOR MUCGIAMGIA

--bo sung cho bang dondathang rang buoc kiem tra ngay giao va ngay chuyen phai sau hoac bang voi ngay dat hang
ALTER TABLE DONDATHANG ADD CONSTRAINT CHK_NGAYGIAOHANG CHECK(NGAYGIAOHANG >= NGAYDATHANG AND NGAYCHUYENHANG >= NGAYDATHANG)

--bo sung rang buoc cho bang nhanvien de dam bao rang 1 nhan vien chi co the lam viec trong cong ty khi du 18 tuoi va khong qua 60 tuoi
ALTER TABLE NHANVIEN ADD CONSTRAINT CHK_TUOI CHECK(DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 18 AND DATEDIFF(YEAR, NGAYSINH, GETDATE()) <= 60)

--voi cac bang da tao, cau lenh DROP TABLE NHACUNGCAP co the thuc hien duoc hay khong va vi sao
--không thể xóa bảng NHACUNGCAP vì nó được tham chiếu từ các ràng buộc khóa ngoại

